# Generated by Django 5.2.9 on 2025-12-27 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'user', 'permission')},
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentcontent',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documentpermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='documentpermission',
            name='creted_at',
        ),
    ]
