# Generated by Django 5.2.9 on 2026-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='locked_password',
            field=models.CharField(blank=True, help_text='Hashed password for locked documents', max_length=128, null=True),
        ),
    ]
