# Generated by Django 5.2.9 on 2026-01-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_locked_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_locked',
        ),
    ]
